<?php
namespace Magenest\SocialLogin\Block\SocialNetwork;

use Magento\Customer\Block\Form\Register;
use Magento\Framework\App\ObjectManager;

class AdditionalInfo extends Register
{
    protected $userData = false;

    public function getUserData()
    {
        $session = ObjectManager::getInstance()->get('Magento\Framework\Session\SessionManagerInterface');
        if (!$this->userData) {
            $this->userData = $session->getUserData();
        }
        return $this->userData;
    }

    public function clearUserData()
    {
        $session = ObjectManager::getInstance()->get('Magento\Framework\Session\SessionManagerInterface');
        $session->setUserData(null);
    }

    public function getFirstName()
    {
        if(isset($this->userData['firstname'])) {
            return $this->userData['firstname'];
        }
        return "";
    }

    public function getLastName()
    {
        if(isset($this->userData['lastname'])) {
            return $this->userData['lastname'];
        }
        return "";
    }

    public function getEmail()
    {
        if(isset($this->userData['email'])) {
            return $this->userData['email'];
        }
        return "";
    }

    protected function _prepareLayout()
    {
        $result = parent::_prepareLayout(); // TODO: Change the autogenerated stub
        $this->pageConfig->getTitle()->set(__('Additional information to complete'));
        return $result;
    }

    public function getSocialLoginType(){
        if(isset($this->userData['magenest_sociallogin_type'])) {
            return $this->userData['magenest_sociallogin_type'];
        }
        return "";
    }

    public function getSocialLoginId(){
        if(isset($this->userData['magenest_sociallogin_id'])) {
            return $this->userData['magenest_sociallogin_id'];
        }
        return "";
    }
}