
<?php if ($block->isGoogleEnabled()): ?>
    <div class="modal-google google_button_connect">
    </div>
<?php endif; ?>


<script>
    require(['jquery','magenestSocialLogin'],
        function($,sociallogin){
            $(document).ready(function () {
                $('.google_button_connect').bind('click',function(){
                    var url = '<?PHP echo $block->getButtonUrl();?>';
                    if (url.length) {
                        sociallogin.display(url, 'Google', 600, 600);
                    }
                });
            })
        })

</script>

