<?php if($block->isInstagramEnabled()): ?>
    <div class="modal-instagram instagram_button_connect">
    </div>
<?php endif;?>


<script>
    require(['jquery','magenestSocialLogin'],
        function($,sociallogin){
            $(document).ready(function () {
                $('.instagram_button_connect').bind('click',function(){
                    var url = '<?PHP echo $block->getButtonUrl();?>';
                    if (url.length) {
                        sociallogin.display(url, 'Instagram', 600, 600);
                    }
                });
            })
        })

</script>

