<?php
/** @var \Magenest\SocialLogin\Block\SocialNetwork\Kakao $block */
if($block->isKakaoEnabled()): ?>
    <div class="modal-kakao kakao_button_connect"></div>
<?php endif;?>


<script>
    require(['jquery','magenestSocialLogin'],
        function($,sociallogin){
            $(document).ready(function () {
                $('.kakao_button_connect').bind('click',function(){
                    var url = '<?PHP echo $block->getButtonUrl();?>';
                    if (url.length) {
                        sociallogin.display(url, 'Kakao', 600, 600);
                    }
                });
            })
        })

</script>
