<?php if($block->isLineEnabled()): ?>
    <div class="modal-line line_button_connect">
    </div>
<?php endif;?>


<script>
    require(['jquery','magenestSocialLogin'],
        function($,sociallogin){
            $(document).ready(function () {
                $('.line_button_connect').bind('click',function(){
                    var url = '<?PHP echo $block->getButtonUrl();?>';
                    if (url.length) {
                        sociallogin.display(url, 'Line', 600, 600);
                    }
                });
            })
        })

</script>

