<?php if($block->isRedditEnabled()): ?>
    <div class="modal-reddit reddit_button_connect">
    </div>
<?php endif;?>


<script>
    require(['jquery','magenestSocialLogin'],
        function($,sociallogin){
            $(document).ready(function () {
                $('.reddit_button_connect').bind('click',function(){
                    var url = '<?PHP echo $block->getButtonUrl();?>';
                    if (url.length) {
                        sociallogin.display(url, 'Reddit', 600, 600);
                    }
                });
            })
        })

</script>

