<?php if ($block->isTwitterEnabled()): ?>
    <div class="modal-twitter twitter_button_connect">
    </div>
<?php endif;?>


<script>
    require(['jquery','magenestSocialLogin'],
        function($,sociallogin){
            $(document).ready(function () {
                $('.twitter_button_connect').bind('click',function(){
                    var url = '<?PHP echo $block->getButtonUrl();?>';
                    if (url.length) {
                        sociallogin.display(url, 'Twitter', 600, 600);
                    }
                });
            })
        })

</script>

