<?php
/** @var \Magenest\SocialLogin\Block\SocialNetwork\Wechat $block */
if($block->isWechatEnabled()): ?>
    <div class="modal-wechat wechat_button_connect"></div>
<?php endif;?>


<script>
    require(['jquery','magenestSocialLogin'],
        function($,sociallogin){
            $(document).ready(function () {
                $('.wechat_button_connect').bind('click',function(){
                    var url = '<?PHP echo $block->getButtonUrl();?>';
                    if (url.length) {
                        sociallogin.display(url, 'Wechat', 600, 600);
                    }
                });
            })
        })

</script>
