<?php
namespace Magenest\SocialLogin\Block;

use Magento\Catalog\Block\Product\Context;
use Magento\Catalog\Block\Product\AbstractProduct;

class Share extends AbstractProduct
{
    /**
     * @var \Magenest\SocialLogin\Model\Share\Share
     */
    protected $_clientShare;

    /**
     * Share constructor.
     * @param Context $context
     * @param \Magenest\SocialLogin\Model\Share\Share $clientShare
     * @param array $data
     */
    public function __construct(
        Context $context,
        \Magenest\SocialLogin\Model\Share\Share $clientShare,
        array $data = [])
    {
        $this->_clientShare = $clientShare;
        parent::__construct($context, $data);
    }

    /**
     * @return bool
     */
    public function isShareEnabled()
    {
        return $this->_clientShare->isEnabled();
    }

    public function getSocialShare()
    {
        return $this->_clientShare->getSocialShare();
    }

    public function getProductUrlForZalo()
    {
        return parent::getProductUrl($this->getProduct()); // TODO: Change the autogenerated stub
    }

    public function getZaloDataId()
    {
        return $this->_scopeConfig->getValue('magenest/credentials/zalo/client_id');
    }

}
